Tue Mar 12 14:58:16 CET 2019 : Apache Derby Network Server - 10.11.1.2 - (1629631) démarré et prêt à accepter les connexions sur le port 1527
----------------------------------------------------------------
Tue Mar 12 14:58:17 CET 2019:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance a816c00e-0169-7232-48e9-000003763d39 
dans le répertoire de base de données C:\Users\thoma\Desktop\HardisGestionClient\ptipote avec le chargeur de classe sun.misc.Launcher$AppClassLoader@266474c2
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_161/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b12
user.dir=C:\Program Files\Java\jdk1.8.0_161\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\thoma\Desktop\HardisGestionClient
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
----------------------------------------------------------------
Tue Mar 12 14:58:19 CET 2019:
Fermeture de l'instance a816c00e-0169-7232-48e9-000003763d39 sur le répertoire de base de données C:\Users\thoma\Desktop\HardisGestionClient\ptipote avec le chargeur de classe sun.misc.Launcher$AppClassLoader@266474c2 
Tue Mar 12 14:58:19 CET 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = ptipote), (DRDAID = {2}), Arrêt de la base de données 'ptipote'.
Tue Mar 12 15:09:43 CET 2019 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Base de données 'ptipote' introuvable.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Base de données 'ptipote' introuvable.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Base de données 'ptipote' introuvable.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Tue Mar 12 15:09:43 CET 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = ptipote), (DRDAID = {3}), Base de données 'ptipote' introuvable.
----------------------------------------------------------------
Tue Mar 12 15:52:44 CET 2019 : fermeture du moteur Derby
----------------------------------------------------------------
